export const MANUFACTURING_ERROR_CODES = Object.freeze({
  INVALID_MANUFACTURING_INPUT: "INVALID_MANUFACTURING_INPUT",
  INVALID_ESTIMATE_ID: "INVALID_ESTIMATE_ID",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  UPLOAD_STATE_INVALID: "UPLOAD_STATE_INVALID",
  UPLOAD_EXPIRED: "UPLOAD_EXPIRED",
  MANUFACTURING_PROFILE_UNAVAILABLE: "MANUFACTURING_PROFILE_UNAVAILABLE",
  MODEL_UNIT_REQUIRED: "MODEL_UNIT_REQUIRED",
  MODEL_UNIT_INVALID: "MODEL_UNIT_INVALID",
  MODEL_NOT_SLICEABLE: "MODEL_NOT_SLICEABLE",
  MODEL_OUTSIDE_BUILD_VOLUME: "MODEL_OUTSIDE_BUILD_VOLUME",
  MODEL_TOO_COMPLEX: "MODEL_TOO_COMPLEX",
  SLICER_PROFILE_INVALID: "SLICER_PROFILE_INVALID",
  SLICER_PROFILE_MISMATCH: "SLICER_PROFILE_MISMATCH",
  SLICER_OUTPUT_INVALID: "SLICER_OUTPUT_INVALID",
  SLICER_UNAVAILABLE: "SLICER_UNAVAILABLE",
  SLICER_TIMEOUT: "SLICER_TIMEOUT",
  SLICER_DOWNLOAD_FAILED: "SLICER_DOWNLOAD_FAILED",
  MANUFACTURING_START_FAILED: "MANUFACTURING_START_FAILED",
  MANUFACTURING_SAVE_FAILED: "MANUFACTURING_SAVE_FAILED",
  WORKER_BUSY: "WORKER_BUSY",
  RATE_LIMITED: "RATE_LIMITED",
  MANUFACTURING_ESTIMATION_FAILED: "MANUFACTURING_ESTIMATION_FAILED"
});

export class ManufacturingClientError extends Error {
  constructor(code, options = {}) {
    super(code, options);
    this.name = "ManufacturingClientError";
    this.code = code;
  }
}
